set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
############## clock define##################
set_property PACKAGE_PIN AB11 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
create_clock -period 40.000 -name sys_clk -waveform {0.000 20.000} [get_ports sys_clk]
############## AN871 LCD##################
set_property PACKAGE_PIN H11    [get_ports {lcd_pwm}]
set_property PACKAGE_PIN J12    [get_ports {lcd_hs}]
set_property PACKAGE_PIN J14    [get_ports {lcd_vs}]
set_property PACKAGE_PIN H12    [get_ports {lcd_dclk}]
set_property PACKAGE_PIN K14    [get_ports {lcd_de}]

set_property PACKAGE_PIN F11    [get_ports {lcd_b[0]}]
set_property PACKAGE_PIN F12    [get_ports {lcd_b[1]}]
set_property PACKAGE_PIN H13    [get_ports {lcd_b[2]}]
set_property PACKAGE_PIN H14	[get_ports {lcd_b[3]}]
set_property PACKAGE_PIN G14    [get_ports {lcd_b[4]}]
set_property PACKAGE_PIN G15	[get_ports {lcd_b[5]}]
set_property PACKAGE_PIN F10	[get_ports {lcd_b[6]}]
set_property PACKAGE_PIN G11    [get_ports {lcd_b[7]}]

set_property PACKAGE_PIN A15	[get_ports {lcd_g[0]}]
set_property PACKAGE_PIN B15    [get_ports {lcd_g[1]}]
set_property PACKAGE_PIN C13    [get_ports {lcd_g[2]}]
set_property PACKAGE_PIN C14    [get_ports {lcd_g[3]}]
set_property PACKAGE_PIN B10    [get_ports {lcd_g[4]}]
set_property PACKAGE_PIN C11    [get_ports {lcd_g[5]}]
set_property PACKAGE_PIN D14    [get_ports {lcd_g[6]}]
set_property PACKAGE_PIN D15    [get_ports {lcd_g[7]}]

set_property PACKAGE_PIN A11    [get_ports {lcd_r[0]}]
set_property PACKAGE_PIN A12 	[get_ports {lcd_r[1]}]
set_property PACKAGE_PIN A13    [get_ports {lcd_r[2]}]
set_property PACKAGE_PIN B13    [get_ports {lcd_r[3]}]
set_property PACKAGE_PIN A14    [get_ports {lcd_r[4]}]
set_property PACKAGE_PIN B14    [get_ports {lcd_r[5]}]
set_property PACKAGE_PIN E13    [get_ports {lcd_r[6]}]
set_property PACKAGE_PIN E14    [get_ports {lcd_r[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {lcd_pwm}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_hs}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_vs}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_dclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_de}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[*]}]

set_property -dict {PACKAGE_PIN F11 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb_tri_io[0]}]
set_property -dict {PACKAGE_PIN F12 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb_tri_io[1]}]
set_property -dict {PACKAGE_PIN H13 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb_tri_io[2]}]
set_property -dict {PACKAGE_PIN H14 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb_tri_io[3]}]
set_property -dict {PACKAGE_PIN G14 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb_tri_io[4]}]
set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb_tri_io[5]}]
set_property -dict {PACKAGE_PIN F10 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb_tri_io[6]}]
set_property -dict {PACKAGE_PIN G11 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb_tri_io[7]}]

set_property -dict {PACKAGE_PIN A15 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb_tri_io[8]}]
set_property -dict {PACKAGE_PIN B15 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb_tri_io[9]}]
set_property -dict {PACKAGE_PIN C13 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb_tri_io[10]}]
set_property -dict {PACKAGE_PIN C14 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb_tri_io[11]}]
set_property -dict {PACKAGE_PIN B10 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb_tri_io[12]}]
set_property -dict {PACKAGE_PIN C11 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb_tri_io[13]}]
set_property -dict {PACKAGE_PIN D14 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb_tri_io[14]}]
set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb_tri_io[15]}]

set_property -dict {PACKAGE_PIN A11 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb_tri_io[16]}]
set_property -dict {PACKAGE_PIN A12 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb_tri_io[17]}]
set_property -dict {PACKAGE_PIN A13 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb_tri_io[18]}]
set_property -dict {PACKAGE_PIN B13 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb_tri_io[19]}]
set_property -dict {PACKAGE_PIN A14 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb_tri_io[20]}]
set_property -dict {PACKAGE_PIN B14 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb_tri_io[21]}]
set_property -dict {PACKAGE_PIN E13 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb_tri_io[22]}]
set_property -dict {PACKAGE_PIN E14 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb_tri_io[23]}]